--[[ MyGame.Sample.Color

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.7

  Declared by  : 
  Rooting type : MyGame.Sample.Function1 ()

--]]

local Color = {
  Red = 0,
  Green = 1,
  Blue = 2,
}

return Color