--[[ MyGame.Sample.Equipment

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.7

  Declared by  : 
  Rooting type : MyGame.Sample.Function1 ()

--]]

local Equipment = {
  NONE = 0,
  Function1 = 1,
  Object1 = 2,
}

return Equipment