--[[ MyGame.Sample.Object1

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 24.3.7

  Declared by  : 
  Rooting type : MyGame.Sample.Function1 ()

--]]

local flatbuffers = require('flatbuffers')

local Object1 = {}
local mt = {}

function Object1.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Name()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:String(self.view.pos + o)
  end
end

function mt:Damage()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int16, self.view.pos + o)
  end
  return 0
end

function Object1.Start(builder)
  builder:StartObject(2)
end

function Object1.AddName(builder, name)
  builder:PrependUOffsetTRelativeSlot(0, name, 0)
end

function Object1.AddDamage(builder, damage)
  builder:PrependInt16Slot(1, damage, 0)
end

function Object1.End(builder)
  return builder:EndObject()
end

return Object1